# Generated by Django 4.1 on 2022-08-25 23:06

from django.db import migrations, models
import turtle


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Familiar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.TextField(max_length=30)),
                ('relacion_familiar', models.TextField(max_length=30)),
                ('fecha_nacimiento', models.DateField(verbose_name=turtle.textinput)),
            ],
        ),
    ]
